### PR TITLE
FLUO-1038 Use try with resources for streams in FluoAdminImpl

### PR DESCRIPTION
**Pull request by kpm1985**
For #1038 use try with resources for all streams, even byte array based streams so we can: 
a) be consistent with streams and use of try with resources
b) if the stream is ever changed to one that _needs_ to be closed it is already wrapped

### CODE REVIEW

**Comment by ctubbsii** [comment]
@kpm1985 If you reference GitHub issues as "Fix #1038" instead of "FLUO-1038" in your commit message, it will auto-close the referenced issue once the PR is merged. The `PROJECT-####` format isn't *wrong*, but it is more typical for projects using JIRA, which this project does not.

Also, there is no need to create an issue *and* a PR if you are submitting them at (or near) the same time. Since PRs *are* issues, the PR will suffice. Typically, an issue is created first, only if the work is not submitted immediately and a placeholder is needed, or if it warrants discussion prior to starting the work, or if it's an umbrella issue covering several subsequent smaller issues/PRs.

**Comment by kpm1985** [comment]
Thank you, I will avoid duplication.

As you noted behavior is a rollover from jira based projects (Nutch/Log4J2)
and I apologise and thank you.

 In Jira you get complained for NOT filing an issue first, I will adapt for
our awesome project.

**Comment by kpm1985** [comment]
As a curiosity there are some errors with OracleService in Eclipse. It is
beyond my current knowledge as their origin or how to fix. (I'm uneducated
w.r.t Thrift).

Does anyone else see these? How can they be fixed? Playing with Thrift is
very dangerous afaik. Thank you.

**Comment by ctubbsii** [comment]
You might be seeing an eclipse bug if you're using Oxygen. I switched to Photon (pre-release) to stop getting compile time errors in eclipse.

**Pull request merged**
