### PR TITLE
Changed drip color of dark logo

### PR DESCRIPTION
**Pull request by KrishAmal**
fixes issue #815

### CODE REVIEW

**Comment by keith-turner** [comment]
@KrishAmal these changes look good. Your commit has an invalid email address, is that what you intended?

**Comment by keith-turner** [comment]
> Perhaps we should pick an entirely different color? Something like a pale/neon yellow?

I think it would be best to discuss this in a separate issue because the light and dark logos would both need to be considered for consistency.  Also, the drip was supposed to be a liquid, presumably water?  So maybe the `u` should change color?  Also, I think this would be best discussed in an issue.  

This PR fixes the problem of the current dark logo not working well with dark backgrounds.

**Comment by ctubbsii** [comment]
Mountain Dew is a yellow fluid, and at least one Fluo contributor drinks excessive quantities of that :smile:

I'm not sure that my comment requires a new issue... consistency and color change wasn't really my point. I was really just thinking about the dark themed image on its own, and whether this particular change makes the dark themed image look better. I'm not convinced it does. It may be more visible, but I think the color similarity with the other blue makes it look somewhat worse.

I only suggested a color change, because I'm not sure a different shade of blue would look any better. But perhaps if we just go for a much lighter blue, near-white, it would look better?

**Comment by keith-turner** [comment]
>  but I think the color similarity with the other blue makes it look somewhat worse.

IMO this is better than the currently checked in version in which the drip is barely visible on a dark background.  

> I only suggested a color change, because I'm not sure a different shade of blue would look any better. But perhaps if we just go for a much lighter blue, near-white, it would look better?

I am not sure, choosing colors is not something I am good at.  If you have something specific in mind it might be helpful to specify the RGB coordinates.

**Comment by ctubbsii** [comment]
I played around with a few settings in GIMP, and I think the dark blue looks way better on a pure black (000000) background, and many other dark background colors (660505, 070858). But it looks terrible on other dark backgrounds, like dark grey (4e4e4e) or dark green (075808). It's probably not so much a matter of "dark background" vs. "light background", but what specific colors.

Maybe this issue needs to be more specific about which background color it looks bad on, so it can be tweaked for that background? For pure black, I think it looks fine as is.

**Comment by ctubbsii** [comment]
For reference, the dark version is currently being used on a dark grey (333333) background at https://fluo.apache.org ; that's probably the background color which is driving this.

**Comment by keith-turner** [comment]
> It's probably not so much a matter of "dark background" vs. "light background", but what specific colors.

Makes sense. Testing with the website would be nice.

The color that prompted me to open the issue was the twitter logo as mentioned in the issue #815 .

**Comment by keith-turner** [comment]
>  I'd be more okay with the same color being used twice.

I am ok with that and I am also ok with the current change.

**Comment by ctubbsii** [comment]
Ah, I took a look at the Twitter logo. I like that color better. It's closer to the original, and sufficiently distinct from the `u` to not bother me, but it may only work on that particular shade of gray background.

To be clear, I think the color in this change is okay also. It's just a bit of an "uncanny valley" sort of thing for me. It's just *so* close but ever so slightly different from the `u`, that it stands out for me as off-putting. But, the color itself isn't a problem. I just think it'd be better if it were more different or identical than in that valley.

In any case, please feel free to adopt whatever you think works best. I'm only offering feedback from one person's pair of eyes, not a `-1`. If it works for everyone else, go for it. :smile:

**Comment by KrishAmal** [comment]
@keith-turner Thanks for pointing it out , it was not intended . I've Changed the Email address.

**Comment by keith-turner** [comment]
@KrishAmal  thanks for the contribution!!  What did you use to edit the SVG file?  If you are interested in making more contributions and would like help finding something then please get in touch.

Is it ok to add you to our [people page](http://fluo.apache.org/people/) as a contributor?  If so, you can give me the info you would like added or you can make a PR to the [people page](https://github.com/apache/fluo-website/blob/gh-pages/pages/people.md) in the [website repo](https://github.com/apache/fluo-website).

Are you ok with mentioning your first contributions on Twitter at [@ApacheFluo](https://twitter.com/apachefluo)?   If so, do you have a twitter username we could mention?

**Comment by KrishAmal** [comment]
> @KrishAmal thanks for the contribution!! What did you use to edit the SVG file? If you are interested in making more contributions and would like help finding something then please get in touch.

@keith-turner My pleasure that i could contribute ! ,  I used Inkscape(v0.91) for the SVG . 
Sure, I'm definitely interested in more contributions , and would really appreciate your help in finding them .

> Is it ok to add you to our people page as a contributor? If so, you can give me the info you would like added or you can make a PR to the people page in the website repo.
Are you ok with mentioning your first contributions on Twitter at @ApacheFluo? If so, do you have a twitter username we could mention?

That sounds great , I'm Okay with both. I will give my info here , 
_Name:_  Amal Krishnan
_Timezone:_   IST

And my twitter username is [@amal_krish](https://twitter.com/amal_krish)

Thanks !

**Pull request merged**
