### PR TITLE
Remove redundant call whos value is not used anyways

### PR DESCRIPTION
**Pull request by kpm1985**
This closes 944

### CODE REVIEW

**Comment by keith-turner** [comment]
@kpm1985  I Am going to wait to merge this until after getting confirmation about the email addr used in the commit.  I asked about this on another PR.

**Comment by kpm1985** [comment]
@keith-turner

I'm not sure what I've screwed up but I'm off to class in a few minutes and
don't want to hold you up while I'm gone, so here is my quick thing I have
going on:

I have two email addresses, they look very similair.

a) kennethpmcfarland@gmail.com - this is a mailing list address I register,
intended as an inbox for the Apache mailing list

b)kennethpaulmcfarland@gmail.com - this is my "real" email, no mailing list
blow this thing up and I use it to write real emails

I will also review the commit best practices, thank you for helping me
improve and sorry for any hassle, I'll be back around noon PT.

**Comment by keith-turner** [comment]
@kpm1985  using a different email addresses is not a problem.  I just want to ensure you are happy w/ the one in the commit.  Once its merged to master we can't change it.  I noticed they are different and wanted to make sure it was not a typo.  It sounds like it was not a typo.  I will still wait for your go ahead.  There is no hurry, just need to get this change in before the next release.

**Comment by kpm1985** [comment]
It's all good go ahead and push the remote changes I'm fine with that email
address being listed I'll fix it in the future don't want to hold you up

**Comment by keith-turner** [comment]
The other thing I mentioned is that when looking at [commits](https://github.com/apache/fluo/commits/master), your recent commits are not linked to your GitHub account.  You can link multiple email addrs to your GH account if you are interested in fixing this.

**Pull request merged**
