### PR TITLE
fixes #976 fixed scan --raw

### LINKED ISSUE #976: fluo scan raw command is not working
I am seeing the following when trying to scan Fluo's raw data.  However, the scan without the raw options works fine.

```
$ fluo scan -a alide --raw
Scanning data in Accumulo directly for 'alide' application.
Exception in thread "main" java.util.NoSuchElementException: fluo.accumulo.instance is not set!
	at org.apache.fluo.api.config.FluoConfiguration.getDepNonEmptyString(FluoConfiguration.java:1202)
	at org.apache.fluo.api.config.FluoConfiguration.getAccumuloInstance(FluoConfiguration.java:477)
	at org.apache.fluo.core.util.AccumuloUtil.getInstance(AccumuloUtil.java:37)
	at org.apache.fluo.core.util.AccumuloUtil.getConnector(AccumuloUtil.java:47)
	at org.apache.fluo.core.util.ScanUtil.scanAccumulo(ScanUtil.java:150)
	at org.apache.fluo.command.FluoScan.main(FluoScan.java:103)

```

### PR DESCRIPTION
**Pull request by keith-turner**

### CODE REVIEW

**Comment by kpm1985** [comment]
Hope it's ok I merged this :)

**Comment by cjmctague** [comment]
@kpm1985 Did you test the functionality of this pull request yourself?

**Comment by kpm1985** [comment]
I tested the scan functionality with/without raw and with/without patch and
what failed before succeeded with patch applied.

The other mvn tests ran good too.

In retrospect I think for a while I will just stick to being very very
humble and just approving and testing PR if that is ok.

**Comment by keith-turner** [comment]
> Hope it's ok I merged this :)

Yeah, its ok.  Each PR just needs approval by one committer who isnt the author.  

Personally I like to squash so there is only one commit, but not everyone shares that preference or cares.

**Comment by keith-turner** [comment]
> In retrospect I think for a while I will just stick to being very very humble and just approving and testing PR if that is ok.

@kpm1985 don't worry about making mistakes.  Everyone else is making them all the time.  We have history can can revert any commits if needed.

**Comment by keith-turner** [comment]
Also, sometime for an issue I like this I will just look at the code and ask the author what testing they did.

**Comment by cjmctague** [comment]
@kpm1985 All good then! I read the "hopefully this was ok" as not checking it before the merge. 
Sorry my misunderstanding.

**Comment by kpm1985** [comment]
@cjmctague - No need to feel bad it was my poor communication.
@keith-turner - To be a committer was a life goal for me, so I've been so happy, I originally missed the invitation too! I get a little nervous about screwing something up because to me this is such a huge privilege, thank you for making me feel calm and comfortable.

**Pull request merged**
